2018-07-25 11:24:41,760 ERROR: Exception on /index [GET] [in /Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Filip/code/python/microblog/app/routes.py", line 28, in index
    posts=posts)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/Filip/code/python/microblog/app/templates/index.html", line 17, in template
    {% endfor %}
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-07-30 19:51:16,514 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 19:56:09,231 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 19:58:08,633 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 19:59:16,389 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:05:19,768 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:05:25,748 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:05:44,629 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:08:21,457 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:11:28,862 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-30 20:12:34,602 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-31 13:47:56,405 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:54]
2018-07-31 23:22:26,625 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:74]
2018-07-31 23:22:34,853 ERROR: Exception on /user/Filip [GET] [in /Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/Users/Filip/code/python/microblog/app/main/routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/Users/Filip/code/python/microblog/app/__init__.py", line 80, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2018-07-31 23:23:58,913 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:74]
