2018-07-31 23:28:31,496 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/microblog/app/auth/routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "/Users/Filip/code/python/microblog/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/Filip/code/python/microblog/app/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('auth.reset_password', token=token, _external=True) }}</p>
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2018-07-31 23:30:35,461 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/microblog/app/auth/routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "/Users/Filip/code/python/microblog/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/Filip/code/python/microblog/app/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('auth.reset_password', token=token, _external=True) }}</p>
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/Filip/code/python/miniconda3/envs/flaskonda/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2018-08-10 23:56:19,191 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:77]
2018-08-10 23:58:18,016 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:77]
2018-08-11 14:59:54,009 INFO: Microblog startup [in /Users/Filip/code/python/microblog/app/__init__.py:77]
